import { Transaction, RiskRule, FraudAlert, InvestigationCase } from './types';

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    transactionId: 'TX-882193',
    customerId: 'CUST-9942',
    customerName: 'Amit K. Sharma',
    customerEmail: 'amit.sharma@example.in',
    merchantId: 'MERCH-4402',
    merchantName: 'CryptoX Exchange India',
    merchantCategory: 'CRYPTOCURRENCY',
    amount: 75000,
    currency: 'INR',
    paymentMethod: 'UPI / RuPay Platinum',
    cardBin: '607189',
    cardLast4: '4190',
    deviceId: 'DEV-9921-X',
    deviceName: 'MacBookPro M3 (New Device)',
    ipAddress: '185.220.101.45',
    ipLocation: 'Frankfurt, DE (Tor Exit Node)',
    locationCity: 'New Delhi',
    locationCountry: 'IND',
    status: 'BLOCKED',
    riskScore: 85,
    riskLevel: 'CRITICAL',
    decision: 'BLOCK',
    ruleScore: 78,
    behavioralScore: 82,
    mlScore: 91,
    explanation: 'High confidence ATO & Velocity anomaly. 8.3x deviation from 30-day average volume with Tor exit node origin and hardware profile mismatch.',
    recommendedAction: 'Immediate Hard Block & Freeze linked UPI handle. Trigger SMS challenge.',
    evaluationTimeMs: 14,
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    riskFactors: [
      {
        factorCode: 'RULE_EXTREME_AMOUNT_ANOMALY',
        factorName: 'Extreme Amount Anomaly',
        weightScore: 30,
        category: 'AMOUNT_ANOMALY',
        details: '8.3x higher than historical 30-day baseline (₹75,000 vs avg ₹9,036).',
        severity: 'CRITICAL',
      },
      {
        factorCode: 'RULE_TOR_PROXY_ATTACK',
        factorName: 'High-Risk Tor Exit Node IP',
        weightScore: 25,
        category: 'NETWORK_IP',
        details: 'IP 185.220.101.45 confirmed on Tor network directory.',
        severity: 'HIGH',
      },
      {
        factorCode: 'RULE_DEVICE_FINGERPRINT_MISMATCH',
        factorName: 'Novel Hardware Signature',
        weightScore: 18,
        category: 'DEVICE',
        details: 'Hardware profile not previously authenticated for UID CUST-9942.',
        severity: 'HIGH',
      },
      {
        factorCode: 'ML_ENSEMBLE_CLUSTER',
        factorName: 'GBDT Fraud Ring Pattern',
        weightScore: 20,
        category: 'ML_ENSEMBLE',
        details: '94.2% match with known credential stuffing and laundering syndicates.',
        severity: 'CRITICAL',
      }
    ]
  },
  {
    transactionId: 'TX-882194',
    customerId: 'CUST-4402',
    customerName: 'Digital Plaza Electronics',
    customerEmail: 'sales@digitalplaza.com',
    merchantId: 'MERCH-8109',
    merchantName: 'Razorpay Gateway Direct',
    merchantCategory: 'CONSUMER_ELECTRONICS',
    amount: 12499,
    currency: 'INR',
    paymentMethod: 'Credit Card / Visa Infinite',
    cardBin: '424242',
    cardLast4: '8831',
    deviceId: 'DEV-1102-M',
    deviceName: 'Samsung Galaxy S24',
    ipAddress: '49.36.12.190',
    ipLocation: 'Bengaluru, IN',
    locationCity: 'Bengaluru',
    locationCountry: 'IND',
    status: 'FLAGGED',
    riskScore: 58,
    riskLevel: 'MEDIUM',
    decision: 'MONITOR',
    ruleScore: 45,
    behavioralScore: 55,
    mlScore: 62,
    explanation: 'First-time transaction in consumer electronics tier. Low IP risk but moderate transaction velocity observed in past 1 hour.',
    recommendedAction: 'Step-up 3DS OTP validation and monitor for follow-up high-ticket items.',
    evaluationTimeMs: 19,
    createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    riskFactors: [
      {
        factorCode: 'RULE_VELOCITY_HOURLY',
        factorName: 'Accelerated Hourly Transactions',
        weightScore: 20,
        category: 'VELOCITY',
        details: '3 transactions across 2 distinct merchants in past 45 minutes.',
        severity: 'MEDIUM',
      },
      {
        factorCode: 'RULE_MERCHANT_CATEGORY_RISK',
        factorName: 'High-Value Electronics Merchant Tier',
        weightScore: 15,
        category: 'RULE_ENGINE',
        details: 'Merchant MCC 5732 flagged with elevated chargeback baseline.',
        severity: 'MEDIUM',
      }
    ]
  },
  {
    transactionId: 'TX-882195',
    customerId: 'CUST-1022',
    customerName: 'Priya Verma',
    customerEmail: 'priya.verma@techcorp.in',
    merchantId: 'MERCH-3321',
    merchantName: 'Swiggy Instamart',
    merchantCategory: 'GROCERIES',
    amount: 2100,
    currency: 'INR',
    paymentMethod: 'UPI / PhonePe',
    cardBin: '508129',
    cardLast4: '1092',
    deviceId: 'DEV-7788-I',
    deviceName: 'iPhone 15 Pro',
    ipAddress: '103.21.144.12',
    ipLocation: 'Mumbai, IN (Airtel Fiber)',
    locationCity: 'Mumbai',
    locationCountry: 'IND',
    status: 'SETTLED',
    riskScore: 12,
    riskLevel: 'LOW',
    decision: 'APPROVE',
    ruleScore: 8,
    behavioralScore: 10,
    mlScore: 14,
    explanation: 'Verified trusted customer. Trusted device profile matched 48 prior successful authorizations.',
    recommendedAction: 'Instant frictionless authorization with zero friction.',
    evaluationTimeMs: 11,
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    riskFactors: []
  },
  {
    transactionId: 'TX-882196',
    customerId: 'CUST-7710',
    customerName: 'Rajesh Kumar',
    customerEmail: 'rajesh.k@cloudservices.org',
    merchantId: 'MERCH-9941',
    merchantName: 'Uber India Mobility',
    merchantCategory: 'RIDE_SHARING',
    amount: 420,
    currency: 'INR',
    paymentMethod: 'UPI / Google Pay',
    cardBin: '401288',
    cardLast4: '3349',
    deviceId: 'DEV-4421-P',
    deviceName: 'Google Pixel 8',
    ipAddress: '122.161.49.88',
    ipLocation: 'Hyderabad, IN (Jio)',
    locationCity: 'Hyderabad',
    locationCountry: 'IND',
    status: 'SETTLED',
    riskScore: 4,
    riskLevel: 'LOW',
    decision: 'APPROVE',
    ruleScore: 0,
    behavioralScore: 5,
    mlScore: 4,
    explanation: 'High trust score (98/100). Routine daily travel route with zero anomalous flags.',
    recommendedAction: 'Instant Approval.',
    evaluationTimeMs: 9,
    createdAt: new Date(Date.now() - 19 * 60 * 1000).toISOString(),
    riskFactors: []
  },
  {
    transactionId: 'TX-882197',
    customerId: 'CUST-1121',
    customerName: 'Gourmet Foods & Luxury Spirits',
    customerEmail: 'orders@gourmetfoods.co',
    merchantId: 'MERCH-1121',
    merchantName: 'Highland Park Retailers',
    merchantCategory: 'LUXURY_RETAIL',
    amount: 8900,
    currency: 'INR',
    paymentMethod: 'Credit Card / Mastercard World',
    cardBin: '542418',
    cardLast4: '7721',
    deviceId: 'DEV-0091-B',
    deviceName: 'Windows 11 Chrome',
    ipAddress: '198.51.100.22',
    ipLocation: 'Dallas, US (VPN Detected)',
    locationCity: 'Delhi / US Anomaly',
    locationCountry: 'IND',
    status: 'FLAGGED',
    riskScore: 72,
    riskLevel: 'HIGH',
    decision: 'REVIEW',
    ruleScore: 68,
    behavioralScore: 70,
    mlScore: 76,
    explanation: 'Geographic jump detected. Card issued in Delhi was swiped via US VPN 12 minutes after local login.',
    recommendedAction: 'Route to manual fraud analyst triage. Require biometric push confirmation.',
    evaluationTimeMs: 23,
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    riskFactors: [
      {
        factorCode: 'RULE_GEO_VELOCITY_IMPOSSIBLE',
        factorName: 'Impossible Geo-Velocity Jump',
        weightScore: 35,
        category: 'VELOCITY',
        details: 'Distance 12,400km traversed in under 15 minutes between authentications.',
        severity: 'HIGH',
      },
      {
        factorCode: 'RULE_VPN_COMMERCIAL',
        factorName: 'Commercial VPN Provider IP',
        weightScore: 20,
        category: 'NETWORK_IP',
        details: 'Data center hosting range flagged (NordVPN exit gateway).',
        severity: 'MEDIUM',
      }
    ]
  },
  {
    transactionId: 'TX-882198',
    customerId: 'CUST-5519',
    customerName: 'Ananya Deshmukh',
    customerEmail: 'ananya.d@fintechlab.io',
    merchantId: 'MERCH-6612',
    merchantName: 'Amazon Pay India',
    merchantCategory: 'E_COMMERCE',
    amount: 4590,
    currency: 'INR',
    paymentMethod: 'Net Banking / HDFC Bank',
    cardBin: '437551',
    cardLast4: '6102',
    deviceId: 'DEV-8821-M',
    deviceName: 'iPad Air 5',
    ipAddress: '157.48.21.90',
    ipLocation: 'Pune, IN',
    locationCity: 'Pune',
    locationCountry: 'IND',
    status: 'SETTLED',
    riskScore: 16,
    riskLevel: 'LOW',
    decision: 'APPROVE',
    ruleScore: 10,
    behavioralScore: 12,
    mlScore: 18,
    explanation: 'Normal consumer basket size with trusted netbanking multi-factor handshake.',
    recommendedAction: 'Standard authorization approval.',
    evaluationTimeMs: 12,
    createdAt: new Date(Date.now() - 32 * 60 * 1000).toISOString(),
    riskFactors: []
  },
  {
    transactionId: 'TX-882199',
    customerId: 'CUST-3310',
    customerName: 'Karan Mehra',
    customerEmail: 'karan.mehra@velocitystream.com',
    merchantId: 'MERCH-7744',
    merchantName: 'Steam Gaming Store',
    merchantCategory: 'DIGITAL_GOODS',
    amount: 980,
    currency: 'INR',
    paymentMethod: 'Prepaid Card / Visa',
    cardBin: '400115',
    cardLast4: '0098',
    deviceId: 'DEV-3390-W',
    deviceName: 'Generic Linux Client (Scripted)',
    ipAddress: '185.191.171.12',
    ipLocation: 'Bucharest, RO',
    locationCity: 'Unknown',
    locationCountry: 'ROU',
    status: 'BLOCKED',
    riskScore: 92,
    riskLevel: 'CRITICAL',
    decision: 'BLOCK',
    ruleScore: 90,
    behavioralScore: 88,
    mlScore: 95,
    explanation: 'Micro-charge card testing attack. 14 attempts with sequential BIN variants detected in past 180 seconds.',
    recommendedAction: 'Blacklist IP range and block card fingerprint across all merchant channels.',
    evaluationTimeMs: 8,
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    riskFactors: [
      {
        factorCode: 'RULE_CARD_TESTING_BURST',
        factorName: 'Card Testing Micro-Charge Burst',
        weightScore: 40,
        category: 'VELOCITY',
        details: '14 sequential attempts with varying CVVs under ₹1,000.',
        severity: 'CRITICAL',
      },
      {
        factorCode: 'RULE_HEADLESS_BROWSER',
        factorName: 'Automated Headless User Agent',
        weightScore: 25,
        category: 'DEVICE',
        details: 'Puppeteer/Playwright browser automation fingerprints present.',
        severity: 'HIGH',
      }
    ]
  }
];

export const INITIAL_RULES: RiskRule[] = [
  {
    id: 'R-101',
    ruleCode: 'RULE_HIGH_VELOCITY_BURST',
    name: 'Rapid Transaction Burst Velocity',
    category: 'VELOCITY',
    severity: 'HIGH',
    impactScore: 30,
    description: 'Triggers when a customer account initiates 5 or more transactions within any 10-minute sliding window.',
    isActive: true,
    totalTriggeredCount: 142,
    decisionAction: 'REVIEW',
    conditionExpression: 'count(transactions, 10m) >= 5'
  },
  {
    id: 'R-102',
    ruleCode: 'RULE_CARD_TESTING_BURST',
    name: 'Card Testing & Micro-Probe Detection',
    category: 'VELOCITY',
    severity: 'CRITICAL',
    impactScore: 40,
    description: 'Detects repetitive micro-charges (under ₹200 / $5) with failing CVVs or rapid card BIN rotations.',
    isActive: true,
    totalTriggeredCount: 98,
    decisionAction: 'BLOCK',
    conditionExpression: 'amount <= 200 && failedCVVCount >= 3 && window == 5m'
  },
  {
    id: 'R-103',
    ruleCode: 'RULE_EXTREME_AMOUNT_ANOMALY',
    name: 'Extreme Amount Anomaly Multiplier',
    category: 'AMOUNT_ANOMALY',
    severity: 'CRITICAL',
    impactScore: 35,
    description: 'Flags transaction volume exceeding 6.0x the customer 30-day rolling baseline average.',
    isActive: true,
    totalTriggeredCount: 312,
    decisionAction: 'REVIEW',
    conditionExpression: 'amount / customer.historical30dAvg >= 6.0'
  },
  {
    id: 'R-104',
    ruleCode: 'RULE_TOR_PROXY_ATTACK',
    name: 'Tor Exit Node & Known Bulletproof Proxy',
    category: 'NETWORK_SECURITY',
    severity: 'HIGH',
    impactScore: 28,
    description: 'Identifies incoming network sessions routed through Tor relays, anonymizer VPNs, or compromised proxies.',
    isActive: true,
    totalTriggeredCount: 89,
    decisionAction: 'BLOCK',
    conditionExpression: 'ip.isTor == true || ip.isAnonymousProxy == true'
  },
  {
    id: 'R-105',
    ruleCode: 'RULE_GEO_VELOCITY_IMPOSSIBLE',
    name: 'Impossible Geographic Velocity',
    category: 'VELOCITY',
    severity: 'HIGH',
    impactScore: 32,
    description: 'Flags physical distance between consecutive transaction coordinates requiring airspeed > 900 km/h.',
    isActive: true,
    totalTriggeredCount: 54,
    decisionAction: 'REVIEW',
    conditionExpression: 'geoDistance(tx_prev, tx_curr) / timeDelta > 900km/h'
  },
  {
    id: 'R-106',
    ruleCode: 'RULE_SUSPICIOUS_DEVICE_CLUSTER',
    name: 'Multi-Account Device Clustering',
    category: 'DEVICE_INTEGRITY',
    severity: 'CRITICAL',
    impactScore: 35,
    description: 'Triggers when a single hardware fingerprint is associated with more than 4 distinct cardholders.',
    isActive: true,
    totalTriggeredCount: 67,
    decisionAction: 'BLOCK',
    conditionExpression: 'device.linkedAccountsCount >= 4'
  },
  {
    id: 'R-107',
    ruleCode: 'RULE_FAILED_BURST_TAKEOVER',
    name: 'Account Takeover Credential Spike',
    category: 'BEHAVIOR',
    severity: 'HIGH',
    impactScore: 30,
    description: 'Flags high-ticket transaction (> ₹10,000) occurring within 2 hours of multiple failed password/PIN attempts.',
    isActive: true,
    totalTriggeredCount: 43,
    decisionAction: 'BLOCK',
    conditionExpression: 'failedLogins24h >= 3 && amount >= 10000'
  }
];

export const INITIAL_ALERTS: FraudAlert[] = [
  {
    alertId: 'ALT-9041',
    transactionId: 'TX-882193',
    customerId: 'CUST-9942',
    customerName: 'Amit K. Sharma',
    merchantId: 'MERCH-4402',
    merchantName: 'CryptoX Exchange India',
    amount: 75000,
    currency: 'INR',
    riskScore: 85,
    riskLevel: 'CRITICAL',
    alertType: 'High-Value ATO Spike',
    status: 'OPEN',
    assignedTo: 'John Doe',
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    riskFactorsSummary: ['8.3x Amount Anomaly', 'Tor Node IP', 'Novel Device Profile']
  },
  {
    alertId: 'ALT-9040',
    transactionId: 'TX-882197',
    customerId: 'CUST-1121',
    customerName: 'Gourmet Foods & Luxury Spirits',
    merchantId: 'MERCH-1121',
    merchantName: 'Highland Park Retailers',
    amount: 8900,
    currency: 'INR',
    riskScore: 72,
    riskLevel: 'HIGH',
    alertType: 'Impossible Geo Velocity',
    status: 'INVESTIGATING',
    assignedTo: 'Sarah Jenkins',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    riskFactorsSummary: ['12,400km jump in 15m', 'Commercial VPN']
  },
  {
    alertId: 'ALT-9039',
    transactionId: 'TX-882199',
    customerId: 'CUST-3310',
    customerName: 'Karan Mehra',
    merchantId: 'MERCH-7744',
    merchantName: 'Steam Gaming Store',
    amount: 980,
    currency: 'INR',
    riskScore: 92,
    riskLevel: 'CRITICAL',
    alertType: 'Card Testing Syndicate',
    status: 'ESCALATED',
    assignedTo: 'John Doe',
    createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    riskFactorsSummary: ['14 Sequential Micro-probes', 'Headless Browser Script']
  },
  {
    alertId: 'ALT-9038',
    transactionId: 'TX-881902',
    customerId: 'CUST-2184',
    customerName: 'Vikramaditya Rao',
    merchantId: 'MERCH-3301',
    merchantName: 'Tata Neu SuperApp',
    amount: 34500,
    currency: 'INR',
    riskScore: 68,
    riskLevel: 'HIGH',
    alertType: 'Device Fingerprint Anomaly',
    status: 'RESOLVED',
    assignedTo: 'Sarah Jenkins',
    resolutionNotes: 'Customer verified via outbound interactive voice response and OTP.',
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    resolvedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    riskFactorsSummary: ['Unrecognized Android Tablet', 'High Ticket Purchase']
  }
];

export const INITIAL_CASES: InvestigationCase[] = [
  {
    caseId: 'CASE-2026-0881',
    title: 'Syndicate Card Testing & Bot Probe Network',
    priority: 'CRITICAL',
    status: 'IN_REVIEW',
    leadAnalyst: 'John Doe',
    targetType: 'DEVICE',
    targetId: 'DEV-3390-W (Cluster 14)',
    totalSuspiciousAmount: 142800,
    currency: 'INR',
    summary: 'Automated bot farm executing micro-validations across gaming and gift-card merchants using stolen BIN databases.',
    linkedTransactions: ['TX-882199', 'TX-882193', 'TX-881804'],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    notes: [
      {
        id: 'NOTE-1',
        caseId: 'CASE-2026-0881',
        author: 'John Doe',
        noteType: 'EVIDENCE',
        noteText: 'Captured HTTP headers reveal headless Chromium user agent string and Romanian datacenter IP pool.',
        createdAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString()
      },
      {
        id: 'NOTE-2',
        caseId: 'CASE-2026-0881',
        author: 'Sarah Jenkins',
        noteType: 'DECISION',
        noteText: 'Blacklisted IP subnet 185.191.171.0/24 across all payment gateways. Added card BINs to watch queue.',
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString()
      }
    ]
  },
  {
    caseId: 'CASE-2026-0879',
    title: 'Account Takeover on High-Net-Worth UPI Accounts',
    priority: 'HIGH',
    status: 'OPEN',
    leadAnalyst: 'Sarah Jenkins',
    targetType: 'CUSTOMER',
    targetId: 'CUST-9942',
    totalSuspiciousAmount: 75000,
    currency: 'INR',
    summary: 'Suspected SIM swap / credential leak leading to rapid off-ramping attempts on CryptoX exchange.',
    linkedTransactions: ['TX-882193'],
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    notes: [
      {
        id: 'NOTE-3',
        caseId: 'CASE-2026-0879',
        author: 'Sarah Jenkins',
        noteType: 'GENERAL',
        noteText: 'Customer registered address in New Delhi. Tx initiated via Frankfurt Tor exit node with immediate crypto purchase intent.',
        createdAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString()
      }
    ]
  }
];
